name: Test composable in emacs

on: [push]

jobs:
  test:
    name: Test ${{ matrix.emacs_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '25.1'
          - '26.3'
          - '27.1'
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: conao3/setup-cask@master

      - name: Build
        shell: bash
        run: cask

      - name: Test
        shell: bash
        run: make test

# A pretty complete example
# https://github.com/szermatt/emacs-bash-completion/blob/fa5557709ee11b41a2b5393efe60cd464c56f76e/.github/workflows/test.yml
